networks:
  ros-network:
    driver: bridge

services:
  roscore:
    image: oucompsci/ros:${rosdockerversion}
    container_name: roscore
    command: roscore
    restart: unless-stopped

    networks:
      - ros-network

  rviz:
    image: oucompsci/ros:${rosdockerversion}
    container_name: rviz
    command: rviz
    depends_on:
      - roscore
    environment:
      - DISPLAY=${DISPLAY}
      - "ROS_MASTER_URI=http://roscore:11311"
      - QT_X11_NO_MITSHM=1 # Fix a bug with QT
    user: ${UID}
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/${USER}:/home/${USER}:rw #share your home with write permissions
    privileged: true
    networks:
      - ros-network
    stdin_open: true
    tty: true

  rosbash:
    image: oucompsci/ros:${rosdockerversion}
    container_name: rosbash
    command: bash
    depends_on:
      - roscore
    networks:
      - ros-network
    environment:
      - "ROS_MASTER_URI=http://roscore:11311"
    stdin_open: true
    tty: true
